### ISSUE TITLE
[cover-router] Update yearly cost (annual price) for product to include commission

### ISSUE THREAD

**Issue by mixplore** [NexusMutual/cover-router#61]
Currently on the quote endpoint, besides premium and pool allocation requests, we get the `annualPrice` value. This value doesn't take into consideration the cover commission (specific to each product, can be passed as query param when calling the endpoint). 
The `annualPrice` value should include the commission. 

Blocking https://github.com/NexusMutual/frontend-next/issues/93

**Comment by roxdanila** [comment]
ideally make the parameter optional and default its value to 0, so it stays backward compatible for others using the endpoint

**Comment by mixplore** [comment]
Yes, we already discussed those details on the previous request for the premiums value (which is similar, adding the commission to premium), this should come as a follow-up on that change.
